version: '3'
services:

 mysql:
    image: mysql
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
          - 3307:3306
            
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda-petshop
volumes:
  mysql-volume:
  